DROP DATABASE X;
CREATE DATABASE X;
USE X;
CREATE TABLE HACKERS(
HACKER_ID int,
NAME VARCHAR(255)
);
CREATE TABLE CHALLENGES(
CHALLENGE_ID INT,
HACKER_ID INT
);

INSERT INTO HACKERS(HACKER_ID,NAME) VALUES (1,'A');
INSERT INTO HACKERS(HACKER_ID,NAME) VALUES (3,'B');
INSERT INTO HACKERS(HACKER_ID,NAME) VALUES (7,'C');
INSERT INTO HACKERS(HACKER_ID,NAME) VALUES (9,'z');
INSERT INTO HACKERS(HACKER_ID,NAME) VALUES (4,'E');
INSERT INTO HACKERS(HACKER_ID,NAME) VALUES (6,'F');
INSERT INTO HACKERS(HACKER_ID,NAME) VALUES (8,'m');
INSERT INTO HACKERS(HACKER_ID,NAME) VALUES (10,'H');
INSERT INTO HACKERS(HACKER_ID,NAME) VALUES (5,'I');
INSERT INTO HACKERS(HACKER_ID,NAME) VALUES (2,'J');

INSERT INTO CHALLENGES(CHALLENGE_ID,HACKER_ID) VALUES (100,2);
INSERT INTO CHALLENGES(CHALLENGE_ID,HACKER_ID) VALUES (101,4);
INSERT INTO CHALLENGES(CHALLENGE_ID,HACKER_ID) VALUES (102,6);
INSERT INTO CHALLENGES(CHALLENGE_ID,HACKER_ID) VALUES (400,8);
INSERT INTO CHALLENGES(CHALLENGE_ID,HACKER_ID) VALUES (87,2);
INSERT INTO CHALLENGES(CHALLENGE_ID,HACKER_ID) VALUES (900,4);
INSERT INTO CHALLENGES(CHALLENGE_ID,HACKER_ID) VALUES (356,6);
INSERT INTO CHALLENGES(CHALLENGE_ID,HACKER_ID) VALUES (301,8);
INSERT INTO CHALLENGES(CHALLENGE_ID,HACKER_ID) VALUES (3010,8);
INSERT INTO CHALLENGES(CHALLENGE_ID,HACKER_ID) VALUES (200,9);
INSERT INTO CHALLENGES(CHALLENGE_ID,HACKER_ID) VALUES (267,9);
INSERT INTO CHALLENGES(CHALLENGE_ID,HACKER_ID) VALUES (239,9);
INSERT INTO CHALLENGES(CHALLENGE_ID,HACKER_ID) VALUES (5,10);
/*
SELECT COUNT(*)
FROM CHALLENGES C2
GROUP BY C2.HACKER_ID
ORDER BY COUNT(C2.HACKER_ID) DESC
LIMIT 1;
*/
SELECT C.HACKER_ID,H.NAME,COUNT(*)
FROM CHALLENGES C
JOIN HACKERS H
ON H.HACKER_ID = C.HACKER_ID
GROUP BY H.HACKER_ID
HAVING COUNT(*) >= (SELECT COUNT(C2.HACKER_ID)
                            FROM CHALLENGES C2
                            GROUP BY C2.HACKER_ID
                            ORDER BY COUNT(C2.HACKER_ID) DESC
                            LIMIT 1)
ORDER BY COUNT(*) DESC,H.HACKER_ID;