SELECT H.HACKER_ID, H.NAME, SUM(S.SCORE)
FROM (SELECT HACKER_ID, CHALLENGE_ID, MAX(SCORE) AS SCORE
    FROM SUBMISSIONS
    GROUP BY HACKER_ID, CHALLENGE_ID)  S
JOIN HACKERS H
ON H.HACKER_ID = S.HACKER_ID
GROUP BY H.HACKER_ID,H.NAME
HAVING SUM(S.SCORE) > 0
ORDER BY SUM(S.SCORE) DESC, H.HACKER_ID ASC;