/*
CREATE DATABASE X;
USE X;
CREATE TABLE STUDENTS(
ID int,
NAME VARCHAR(255),
MARKS INT);
CREATE TABLE GRADES(
GRADE INT,
MIN_MARK INT ,
MAX_MARK INT);

INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (1,'Q',9);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (2,'W',19);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (3,'E',29);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (4,'R',39);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (5,'T',49);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (6,'Y',59);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (7,'U',69);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (8,'I',79);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (9,'O',89);
INSERT INTO STUDENTS(ID,NAME,MARKS) VALUES (10,'P',99);

INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (1,0,9);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (2,10,99);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (3,20,19);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (4,30,89);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (5,40,29);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (6,50,79);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (7,60,39);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (8,70,69);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (9,80,49);
INSERT INTO GRADES(GRADE,MIN_MARK,MAX_MARK) VALUES (10,90,50);
*/
SELECT IF(G.GRADE >= 8, S.NAME, NULL), G.GRADE, S.MARKS
FROM STUDENTS S
JOIN GRADES G
WHERE G.MIN_MARK <= S.MARKS AND S.MARKS <= G.MAX_MARK
ORDER BY G.GRADE DESC, S.NAME;